services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flat-budget-api-container
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: flat-budget-mongodb-container
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminHeslo420
      MONGO_INITDB_DATABASE: flat-budget
    volumes:
      - flat-budget-mongo-data:/data/db

volumes:
  flat-budget-mongo-data:
